#!/bin/bash
# ===========================================
# TatvaOps Vision - Generate Environment Variables from Terraform
# ===========================================
#
# This script generates .env files from Terraform outputs
#
# Usage:
#   ./generate-env.sh [environment]
#
# Example:
#   ./generate-env.sh production
#
# ===========================================

set -e

ENVIRONMENT=${1:-production}
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="$SCRIPT_DIR/../terraform"
PROJECT_ROOT="$SCRIPT_DIR/../.."

echo "🔧 Generating environment files for: $ENVIRONMENT"

# Check if Terraform is installed
if ! command -v terraform &> /dev/null; then
    echo "❌ Terraform is not installed. Please install Terraform first."
    exit 1
fi

# Check if jq is installed
if ! command -v jq &> /dev/null; then
    echo "❌ jq is not installed. Please install jq first."
    exit 1
fi

# Navigate to Terraform directory
cd "$TERRAFORM_DIR"

# Check if Terraform state exists
if [ ! -f "terraform.tfstate" ] && [ ! -d ".terraform" ]; then
    echo "❌ Terraform state not found. Run 'terraform init' and 'terraform apply' first."
    exit 1
fi

echo "📥 Fetching Terraform outputs..."

# Get outputs
RDS_ENDPOINT=$(terraform output -raw rds_endpoint 2>/dev/null || echo "")
RDS_ADDRESS=$(terraform output -raw rds_address 2>/dev/null || echo "")
RDS_PORT=$(terraform output -raw rds_port 2>/dev/null || echo "5432")
RDS_DATABASE=$(terraform output -raw rds_database_name 2>/dev/null || echo "tatvaops_vision")
RDS_SECRET_ARN=$(terraform output -raw rds_secret_arn 2>/dev/null || echo "")

REDIS_URL=$(terraform output -raw redis_url 2>/dev/null || echo "")

SQS_FLOORPLAN=$(terraform output -json sqs_queue_urls 2>/dev/null | jq -r '.floorplan_analysis' || echo "")
SQS_MOODBOARD=$(terraform output -json sqs_queue_urls 2>/dev/null | jq -r '.moodboard_generation' || echo "")
SQS_INTERIOR=$(terraform output -json sqs_queue_urls 2>/dev/null | jq -r '.interior_view_generation' || echo "")
SQS_COMPONENT=$(terraform output -json sqs_queue_urls 2>/dev/null | jq -r '.component_update' || echo "")
SQS_NOTIFICATION=$(terraform output -json sqs_queue_urls 2>/dev/null | jq -r '.notification' || echo "")

S3_FLOORPLANS=$(terraform output -json s3_bucket_names 2>/dev/null | jq -r '.floorplans' || echo "")
S3_MOODBOARDS=$(terraform output -json s3_bucket_names 2>/dev/null | jq -r '.moodboards' || echo "")
S3_RENDERS=$(terraform output -json s3_bucket_names 2>/dev/null | jq -r '.renders' || echo "")
S3_EXPORTS=$(terraform output -json s3_bucket_names 2>/dev/null | jq -r '.exports' || echo "")

echo "🔐 Retrieving database password from Secrets Manager..."

# Get database password from Secrets Manager
if [ -n "$RDS_SECRET_ARN" ]; then
    DB_PASSWORD=$(aws secretsmanager get-secret-value \
        --secret-id "$RDS_SECRET_ARN" \
        --query 'SecretString' \
        --output text | jq -r '.password')
else
    echo "⚠️  Warning: Could not find RDS secret ARN. Using placeholder."
    DB_PASSWORD="YOUR_PASSWORD_HERE"
fi

# Generate DATABASE_URL
if [ -n "$RDS_ADDRESS" ]; then
    DATABASE_URL="postgresql://tatvaops_admin:${DB_PASSWORD}@${RDS_ENDPOINT}/${RDS_DATABASE}"
else
    DATABASE_URL="postgresql://tatvaops_admin:${DB_PASSWORD}@localhost:5432/tatvaops_vision"
fi

echo "📝 Generating backend .env file..."

# Create backend .env
cat > "$PROJECT_ROOT/backend/.env" << EOF
# ===========================================
# TatvaOps Vision - Backend Configuration
# Generated by generate-env.sh on $(date)
# Environment: $ENVIRONMENT
# ===========================================

# Server
PORT=4000
NODE_ENV=$ENVIRONMENT
CORS_ORIGINS=http://localhost:3000
SERVICE_NAME=tatvaops-vision-api

# Database (AWS RDS PostgreSQL)
DATABASE_URL=$DATABASE_URL
DATABASE_POOL_MIN=2
DATABASE_POOL_MAX=10
DATABASE_CONNECTION_TIMEOUT=5000

# Redis (AWS ElastiCache)
REDIS_URL=$REDIS_URL
REDIS_ENABLED=true
REDIS_FAIL_SOFT=true

# Clerk Authentication
CLERK_SECRET_KEY=
CLERK_WEBHOOK_SECRET=

# AWS General (leave empty if using IAM roles)
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_REGION=ap-south-1

# AWS S3 Buckets
S3_BUCKET_FLOORPLANS=$S3_FLOORPLANS
S3_BUCKET_MOODBOARDS=$S3_MOODBOARDS
S3_BUCKET_RENDERS=$S3_RENDERS
S3_BUCKET_EXPORTS=$S3_EXPORTS
S3_SIGNED_URL_EXPIRY=3600

# AWS SQS Queues
SQS_QUEUE_FLOORPLAN_ANALYSIS=$SQS_FLOORPLAN
SQS_QUEUE_MOODBOARD_GENERATION=$SQS_MOODBOARD
SQS_QUEUE_INTERIOR_VIEW_GENERATION=$SQS_INTERIOR
SQS_QUEUE_COMPONENT_UPDATE=$SQS_COMPONENT
SQS_QUEUE_NOTIFICATION=$SQS_NOTIFICATION

# SQS Settings
SQS_VISIBILITY_TIMEOUT=300
SQS_MAX_RECEIVE_COUNT=3

# AWS SES (Email)
SES_FROM_EMAIL=noreply@tatvaops.com
SES_REPLY_TO_EMAIL=support@tatvaops.com
SES_CONFIGURATION_SET=tatvaops-production

# AWS CloudWatch
CLOUDWATCH_ENABLED=true
CLOUDWATCH_LOG_GROUP=/tatvaops/vision
CLOUDWATCH_LOG_STREAM=

# Google Gemini AI
GEMINI_API_KEY=AIzaSyCzgs9zeMtsnwWoJnZeKspW704MYWdaA3g
GEMINI_MODEL=gemini-pro-vision

# Razorpay Payments
RAZORPAY_KEY_ID=
RAZORPAY_KEY_SECRET=
RAZORPAY_WEBHOOK_SECRET=

# MSG91 (WhatsApp)
MSG91_AUTH_KEY=
MSG91_SENDER_ID=
MSG91_TEMPLATE_ID=
MSG91_ENABLED=false

# Rate Limiting
RATE_LIMIT_WINDOW_MS=60000
RATE_LIMIT_MAX_REQUESTS=100
RATE_LIMIT_AI_WINDOW_MS=60000
RATE_LIMIT_AI_MAX_REQUESTS=10

# Feature Flags
FEATURE_MOODBOARD_V2=false
FEATURE_3D_PREVIEW=false
FEATURE_COMPONENT_INJECTION=false
FEATURE_WHATSAPP_NOTIFICATIONS=false

# Worker Settings
WORKER_CONCURRENCY=2
WORKER_POLL_INTERVAL=20
EOF

echo "📝 Generating worker .env file..."

# Create worker .env
cat > "$PROJECT_ROOT/worker/.env" << EOF
# ===========================================
# TatvaOps Vision - Worker Configuration
# Generated by generate-env.sh on $(date)
# Environment: $ENVIRONMENT
# ===========================================

NODE_ENV=$ENVIRONMENT
SERVICE_NAME=tatvaops-vision-worker

# Database (AWS RDS PostgreSQL)
DATABASE_URL=$DATABASE_URL

# Redis (AWS ElastiCache)
REDIS_URL=$REDIS_URL

# AWS General (leave empty if using IAM roles)
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_REGION=ap-south-1

# AWS S3 Buckets
S3_BUCKET_FLOORPLANS=$S3_FLOORPLANS
S3_BUCKET_MOODBOARDS=$S3_MOODBOARDS
S3_BUCKET_RENDERS=$S3_RENDERS
S3_BUCKET_EXPORTS=$S3_EXPORTS

# AWS SQS Queues
SQS_QUEUE_FLOORPLAN_ANALYSIS=$SQS_FLOORPLAN
SQS_QUEUE_MOODBOARD_GENERATION=$SQS_MOODBOARD
SQS_QUEUE_INTERIOR_VIEW_GENERATION=$SQS_INTERIOR
SQS_QUEUE_COMPONENT_UPDATE=$SQS_COMPONENT
SQS_QUEUE_NOTIFICATION=$SQS_NOTIFICATION

# AWS SES (Email)
SES_FROM_EMAIL=noreply@tatvaops.com
SES_REPLY_TO_EMAIL=support@tatvaops.com

# Google Gemini AI
GEMINI_API_KEY=AIzaSyCzgs9zeMtsnwWoJnZeKspW704MYWdaA3g
GEMINI_MODEL=gemini-pro-vision

# MSG91 (WhatsApp)
MSG91_AUTH_KEY=
MSG91_SENDER_ID=
MSG91_TEMPLATE_ID=

# Worker Settings
WORKER_CONCURRENCY=2
WORKER_POLL_INTERVAL=20

# CloudWatch
CLOUDWATCH_ENABLED=true
CLOUDWATCH_LOG_GROUP=/tatvaops/vision-worker
EOF

echo ""
echo "✅ Environment files generated successfully!"
echo ""
echo "📁 Files created:"
echo "   - $PROJECT_ROOT/backend/.env"
echo "   - $PROJECT_ROOT/worker/.env"
echo ""
echo "⚠️  IMPORTANT: You still need to manually add:"
echo "   - CLERK_SECRET_KEY"
echo "   - CLERK_WEBHOOK_SECRET"
echo "   - GEMINI_API_KEY"
echo "   - RAZORPAY_KEY_ID"
echo "   - RAZORPAY_KEY_SECRET"
echo "   - RAZORPAY_WEBHOOK_SECRET"
echo "   - MSG91_AUTH_KEY (if using WhatsApp)"
echo ""

